meta_product_name: "LIV"
meta_title: "LIV - version bêta"
meta_description: "Liv est un outil d'accompagnement pour que les victimes
ne se sentent plus seules et les encourage à agir,
de manière intuitive et en douceur, et nous l’espérons à se sentir libres. "
meta_image: "liv-logo.jpg" # should exist in `app/assets/images/`
